### ISSUE TITLE
Visualizer for Caltech Lanes Dataset

### ISSUE THREAD

**Issue by sandeepnmenon** [eeyrw/LaneDatasetInspector#1]
Dataset: http://www.mohamedaly.info/datasets/caltech-lanes

I see only matlab implementation for visualising: https://github.com/mohamedadaly/caltechcv-image-labeler

I am writing a Python implementation and would like to add to this repo.

**Comment by eeyrw** [comment]
Thank for sharing your code and I will point out your work at README.MD.

**Comment by sandeepnmenon** [comment]
Thank you. Write now I am using a cubic spline to join the 4 points that represents the lane.
I need to further understand the matlab code by the author to see if any extrapolation is done. Will raise PR with that change then.
